services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MIKRO_ORM_HOST=db
    ports:
      - '3000:3000'
    depends_on:
      - db
      - caddy

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: default-db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  caddy:
    image: caddy:2
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  pgdata:
  caddy_data:
  caddy_config:
